server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certs/bankcards.p12
    key-store-password: fpavel
    key-alias: bankcards

spring:
  application:
    name: bankcards
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: bankcards_admin
    password: passwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO

#
#Что нужно сделать:
#  - Настроить параметры безопасности и JWT.
